### ISSUE TITLE
Add emailVerificationStatus to Account

### ISSUE THREAD

**Issue by jhericks** [stormpath/stormpath-sdk-java#1020]
There's a new property available on REST Account for the emailVerificationStatus.  This should be exposed in the SDK as well.  Valid values are `VERIFIED`, `UNVERIFIED` and `UNKNOWN`.  (`UKNOWN` is for accounts that were created before there was a separate value for email verification, so we can't be sure of the verification status.)

**Comment by jhericks** [comment]
BTW, this will not be in the public API until this week's release is deployed.

**Comment by mzumbadoate** [comment]
This field is added in the PR https://github.com/stormpath/stormpath-sdk-java/pull/1023
BUT the TCK is blocking this PR #1023 since this new field is not yet in the Spec.
The TCK fix to add this field is already created and PR waiting for review and approval in
https://github.com/stormpath/stormpath-framework-tck/pull/319

**Comment by dogeared** [comment]
The TCK issue has been resolved, so this is no longer blocked
