### ISSUE TITLE
Issue 849 was wrongly implemented -> "RelayState" is missing and "state" is broken

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#1030]
https://github.com/stormpath/stormpath-sdk-java/issues/849 wrongly used the `state` property instead of a adding a new `RelayState` property (or `relayState`, not sure which is the actual claim that IDSite and SAML are expecting)

The implementation of issue 849 has broken the functionality described [here](https://docs.stormpath.com/java/apidocs/com/stormpath/sdk/idsite/IdSiteUrlBuilder.html#setState-java.lang.String-) and [here](https://docs.stormpath.com/java/product-guide/latest/idsite.html#how-does-id-site-work). 

The Java SDK will redirect you to whatever was set in `state`. This means that if you set `state = blah` then after a successful authentication your application will try to open `http://localhost:8080/blah`

The changes introduced in #849 must be undone and #849 must be properly implemented.

**Comment by jarias** [comment]
Reference PR of #849 https://github.com/stormpath/stormpath-sdk-java/pull/931/files

**Comment by jarias** [comment]
I think state is the correct claim RelayState is a SAML concept described here https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#step-5a-generate-defaultrelaystate-idp-initiated-authentication-only. The state claim is the only way to get something back in the callback from Social or SAML, if we use a different claim we won't get it back, maybe the issue is the format of the state, right now is just a String maybe it should be a JWT that contains a next claim, so we know is a state that we created and only then redirect to that next claim, if the developer chooses to create their own Social login or SAML  controller then whatever state they choose to pass won't match the one we create and we won't redirect to what ever they use as the state.

Hope this makes sense @mrioan

**Comment by mrioan** [comment]
@jarias the way I see it is that this issue needs to be broken into 2 pieces. It seems that the `relay state` and the `state` were confused. What I think we need to do is:

1. Support relay state for SAML (and IDSIte??) as issue https://github.com/stormpath/stormpath-sdk-java/issues/849 originally requested
2. Make sure the `state` property keeps working just fine with IDSIte: https://docs.stormpath.com/rest/product-guide/latest/idsite.html#idsite-auth-jwt

**Comment by mrioan** [comment]
This issue is now divided in two different issues: https://github.com/stormpath/stormpath-sdk-java/issues/1040 and https://github.com/stormpath/stormpath-sdk-java/issues/1041. I am closing this issue now...
