### ISSUE TITLE
Native Spring Boot Support

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#141]
Create and publish the following spring boot plugins:

* `spring-boot-starter-stormpath`: automatically bootstrap `stormpathClient` and `stormpathApplication` instances into the Spring ApplicationContext at app startup

* `spring-boot-starter-stormpath-web`: build upon `spring-boot-starter-stormpath` to automate the same UI and authentication support that exists in the general [Servlet Plugin](https://docs.stormpath.com/java/servlet-plugin/).

**Comment by lhazlewood** [comment]
Per commit [9aa5110](https://github.com/stormpath/stormpath-sdk-java/commit/9aa51107c0f1c91b7b38ea89753970e18b4c5c2b), `spring-boot-starter-stormpath` works.  Now we need the web integration.

**Comment by jarias** [comment]
Hi @lhazlewood I was playing with the servlet plugin stuff and spring-boot and found the following issues:

1. JSP support in spring-boot using a Jar file as deployment artifact is not supported, see https://github.com/spring-projects/spring-boot/issues/383 and it seems is not going to be supported.

2. Also in a Jar deployment the DefaultConfigLoaderListener doesn't work apparently due to Servlet Spec violation trying to get sessionCookieConfig from the servlet context. see https://github.com/spring-projects/spring-boot/issues/633

I manage to work around this issue with the same approach in the ticket above.

4. In a war deployment things work a bit more smoothly but not entirely, I get random errors again with the JSPs seems like they can't be read properly from the Jar file ```java.lang.IllegalStateException: zip file closed``` again this happens at random but once it happens that specific JSP won't work anymore.

Would be nice if the servlet plugin works fine in both jar and war deployments. And it looks like JSPs are not going to work with spring-boot jars. 

I think a solution is to use Thymeleaf template engine instead of JSPs.

We can talk more on monday.

**Comment by jarias** [comment]
Here is the sample spring-boot app for a Jar deployment.

```
package demo;

import com.stormpath.sdk.servlet.config.ConfigLoader;
import com.stormpath.sdk.servlet.filter.StormpathFilter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.embedded.FilterRegistrationBean;
import org.springframework.boot.context.embedded.ServletContextInitializer;
import org.springframework.context.annotation.Bean;

import javax.servlet.DispatcherType;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import java.util.EnumSet;

@SpringBootApplication
public class DemoApplication implements ServletContextInitializer {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        new ConfigLoader().createConfig(servletContext);
        servletContext.addListener(com.stormpath.sdk.servlet.client.DefaultClientLoaderListener.class);
        servletContext.addListener(com.stormpath.sdk.servlet.application.DefaultApplicationLoaderListener.class);
    }

    @Bean
    public FilterRegistrationBean filterRegistrationBean() {
        EnumSet<DispatcherType> disps = EnumSet.of(
                DispatcherType.REQUEST,
                DispatcherType.FORWARD,
                DispatcherType.INCLUDE,
                DispatcherType.ERROR
        );

        FilterRegistrationBean registrationBean = new FilterRegistrationBean();

        registrationBean.setFilter(new StormpathFilter());
        registrationBean.setDispatcherTypes(disps);
        registrationBean.addUrlPatterns("/*");

        return registrationBean;
    }
}
```

**Comment by lhazlewood** [comment]
Hi @jarias,

Thanks for taking a look in to this!  Please see my replies below:

1.  JSP rendering via a web-fragment.xml is a Servlet 3.0+ container feature and will work on Tomcat 7 and Jetty 8.  If we can enable the existing Stormpath Servlet Plugin and then leverage Spring boot on top of that, it might work.

2.  This shouldn't be an issue if the Spring Boot stuff works 'on top of' the Stormpath Servlet Plugin (which works via a web-fragment.xml)

I agree that it'd be nicer if it was more natively implemented.  I was talking w/ @joshlong of the Spring team before I got sick last week to understand how to do this natively.  It is a challenge: it does not seem that most other web-specific spring boot starters do implement UIs out of the box, and there may not be good support for this yet in Spring Boot - we'll see.

In the [spring](https://github.com/stormpath/stormpath-sdk-java/tree/spring) branch, I just added a spring-boot-starter-stormpath-web module that will attempt this level of integration.  This is only the first step - a lot is left to be done, but we'll see if we can get it working.  I'll see if I can append to this ticket some of my and Josh's conversation to elucidate our current brainstorming approach.

**Comment by jarias** [comment]
1. Even if the fragment is enable apparently there is no way to render JSP if you deploy via Jar with embedded Tomcat or Jetty at least according to the ticket I mention, the app I create is the same as using the plugin just doing it manually instead of getting picked up by the container (don't know why the embedded container doesn't pick up the web fragment.)

2. Might be, but still have the JSP issue.

Again the main issue is only for Jar package spring-boot apps.

**Comment by lhazlewood** [comment]
Yeah.  I'm not against re-writing the templates in any other supported template mechanism if we have to. Any particular reason why you mentioned Thymeleaf?  Why that over others?

**Comment by jarias** [comment]
Nothing specific, the spring team promotes it a lot, thats probably why, but it could be anything really. 

Would be nice to a template language thats implemented in different languages (Go, Python, Node, etc) but I couldn't found one, just because we could reuse the files in other SDKs.

**Comment by lhazlewood** [comment]
Handlebars?

**Comment by lhazlewood** [comment]
Jade seems to be popular across platforms too.

**Comment by jarias** [comment]
Could be, is there a good engine in Java?

**Comment by lhazlewood** [comment]
https://github.com/domix/spring-boot-starter-jade4j

**Comment by lhazlewood** [comment]
Closing per the 1.0.RC4 release
