### ISSUE TITLE
verifyAccountEmail should be on Application (JSDK-197)

### ISSUE THREAD

**Issue by chrylis** [stormpath/stormpath-sdk-java#188]
The `verifyAccountEmail` method on `TenantActions` seems to be misplaced. Account creation, password management, and even resending the verification e-mail are all on `Application`.

**Comment by marioan** [comment]
@chrylis thanks for pointing this out. `Accounts` actually reside inside `Directories` rather than in `Applications`. However, we could add a convenience method in the application to provide the verification of the account's email. This may help developers to find the method since, as you mentioned, the `VerificationEmailRequest` is actually executed from within the Application resource.

BTW, Account creation can also be triggered from a Directory: `http://docs.stormpath.com/java/apidocs/com/stormpath/sdk/directory/Directory.html#createAccount-com.stormpath.sdk.account.Account-`

Thanks!

**Comment by mrioan** [comment]
This feature will not be implemented.
