### ISSUE TITLE
When IDSite is enabled going to `http://localhost:8080/change` does not work

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#297]
If we go to `http://localhost:8080/change` appending the received token we get the home page rather than the "Change your password" page

**Comment by mzumbadoate** [comment]
closing this issue
When IDSite is active the forgot/reset password sends an e-mail with the end point 
https://<URL>/#reset?jwt=TOKEN
and that jwt includes the sp_token
the link shows the change password page correctly, then the /change?sptoken is not used for IDSite
this means that there is nothing to fix because there is nothing broken here
