### ISSUE TITLE
Stormpath RequestEventListener does not work when SpringSecurity is enabled

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#367]
For example, when SS LogoutHandlers are present in the Spring ApplicationContext, our StormpathHttpServletRequest.logout() method is not invoked - which in turn does not invoke our request event publisher.  Need to find another way of ensuring these events are triggered when SS is enabled.

**Comment by dogeared** [comment]
I think this may be related to why when you register with email verification *disabled* and Spring Security enabled, you end up in a state where you *seem* to be logged in, but the `StormpathLoginSuccessHandler`'s `onAuthenticationSuccess` method is never hit.

**Comment by mrioan** [comment]
Hey @lhazlewood I might not be understanding the problem here. We have a `TokenRevocationRequestEventListener` which is properly working with Spring Security.

In `AbstractStormpathWebMvcConfiguration` we have this piece of code

```
public Publisher<RequestEvent> stormpathRequestEventPublisher() {
        List<RequestEventListener> listeners = new ArrayList<RequestEventListener>();
        listeners.add(stormpathRequestEventListener());
        listeners.add(new TokenRevocationRequestEventListener()); //revoke access and refresh tokens after logout
        return new RequestEventPublisher(listeners);
    }
```

The `TokenRevocationRequestEventListener` is properly reacting to the `on(LogoutRequestEvent)` event.

So, if what you are seeing requires some design change please be aware of having the `TokenRevocationRequestEventListener` still reacting to logouts.

**Comment by mrioan** [comment]
BTW, we also have that listener in the Servlet plugin but it is not being used with Spring Security.

`EventPublisherFactory`:

```
@Override
    protected Publisher createInstance(ServletContext servletContext) throws Exception {
        RequestEventListener configuredListener = getConfig().getInstance(REQUEST_EVENT_LISTENER);
        List<RequestEventListener> listeners = new ArrayList<RequestEventListener>();
        listeners.add(configuredListener);
        listeners.add(tokenRevocation);
        return new RequestEventPublisher(listeners);
    }
```

**Comment by lhazlewood** [comment]
@mrioan I don't know if this is still a problem.  If a listener is called on all 5 events when Spring security is enabled, then there is nothing to do.  I need to run a test to verify though.

**Comment by lhazlewood** [comment]
Using the example application in `examples/spring-security-webmvc` only the `FailedAuthenticationRequestEvent` is never received by the `RequestEventListenerAdapter` implementation.  All other event handler methods are invoked.

I'll focus my effort on that event.

**Comment by mrioan** [comment]
Just sharing here possible code that could be useful for this issue: https://github.com/stormpath/stormpath-sdk-java/commit/ccb310e6747dde8f73ed0cc1163e9f1deb408881

Relevant aspects of that code:

1. New filter called `StormpathSpringSecurityUsernamePasswordAuthenticationFilter` that overrides Spring Security's UsernamePasswordAuthenticationFilter functionality of catching username and password from the request
2. This new filter uses `StormpathWebAuthenticationDetailsFactory` to add a map with new information (just the account store right now) to the `UsernamePasswordAuthenticationToken` using `UsernamePasswordAuthenticationToken#setDetails(Object)`
3. For the events we could try something similar in order to save and obtain the original request in the authentication attempt

**Comment by mraible** [comment]
I checked out this branch and ran `examples/spring-security-webmvc` locally. I was able to debug and confirm that `StormpathLogoutHandler#logout` is called when you hit http://localhost:8080/logout. Therefore, :+1:

**Comment by mrioan** [comment]
@mraible am I wrong or your last comment was intended to be for #513 ?

**Comment by mraible** [comment]
Whoops, I meant to leave it on PR #564, not the issue.

**Comment by lhazlewood** [comment]
@mrioan when would that code be available in master?  I can't depend on it for this issue until then.

**Comment by lhazlewood** [comment]
@mrioan nm, I merged already in the spirit of moving forward given that you approved the PR after you made your above comment :)  That said, yeah, that code is a good reference for cleaning this up after that code is merged.
