### ISSUE TITLE
java.lang.IllegalArgumentException while getting Application in 1.0RC3.1

### ISSUE THREAD

**Issue by shikha-G** [stormpath/stormpath-sdk-java#406]
I am facing error as follows:

Exception in thread "main" java.lang.IllegalArgumentException: It is expected that only ArrayProperty properties represent collection items.
	at com.stormpath.sdk.lang.Assert.isTrue(Assert.java:33)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.cache(DefaultDataStore.java:749)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.cache(DefaultDataStore.java:760)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.retrieveResponseValue(DefaultDataStore.java:320)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:215)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:206)
	at com.stormpath.sdk.impl.tenant.DefaultTenant.getApplications(DefaultTenant.java:140)

My code is:

ApiKey apiKey = ApiKeys.builder().setId("<MYKEY>").setSecret("<MYSECRET>").build();
 Client client = Clients.builder().setApiKey(apiKey).build();
Tenant tenant = client.getCurrentTenant();
ApplicationList applications = tenant.getApplications(Applications.where(Applications.name().eqIgnoreCase("My Application")));

Strangely, this was working fine till yesterday and started giving error today only. There has not been any change from our side.

**Comment by relluf** [comment]
We are facing the same exception while logging in with Shiro:

		UsernamePasswordToken token = new UsernamePasswordToken(account,
				password);
		Subject subject = SecurityUtils.getSubject();
		subject.login(token);

**Comment by probal** [comment]
Exact same problem we are facing today. It was working fine yesterday.

**Comment by francisdb** [comment]
Same problem with `1.0.RC5.3` will try `1.0.RC7.4` now

**Comment by francisdb** [comment]
Fixed in `1.0.RC7.4`

**Comment by francisdb** [comment]
see http://status.stormpath.com/incidents/bxhx2zrrmjn0 for more info on this issue

**Comment by shikha-G** [comment]
This caused our production environment down for 5-6 hours at-least. Since we are on IST timezone, didn't get any update from Stormpath as well. As a workaround, we had to make local change in Stormpath-sdk and replace it in our production server. 
This is really unexpected and forcing us to explore alternatives.

**Comment by lhazlewood** [comment]
Hi @shikha-G, @relluf, @probal, @francisdb and our other amazing customers,

Les from Stormpath here. As CTO, among other things, I also head up work on the Java SDK and wanted to chime in even though the issue has since been closed.

First, I sincerely apologize for the issues this bug caused to your team and your users. We completely agree that we should have been more responsive with upgrade instructions and quicker to update [https://status.stormpath.com](https://status.stormpath.com).

Myself and the engineering team spent most of yesterday in post-mortem meetings and implementing a new layer of SDK tests as part of our automated release process of the API. Monday's API release was the only time we've ever broken backwards compatibility in an SDK with an API release in our company's history, and we hope to make it the last.  I'd really like to convey this was an anomaly and it is very unlikely to happen in the future, especially given the improvements we made as part of the post-mortem, and our historical track record hopefully indicates how sincere we are about this.

In addition to this work, our team released a new version of the API today that provides a backwards-compatible solution for teams using a pre-1.0.RC7.4 version of the Java SDK - those teams are now no longer forced to upgrade (but we still encourage it due to the performance enhancements and bug fixes in the latest SDK).

Security and availability are **by far** my two highest priorities and we do everything we can think of to maintain both on the community cloud API. However, if you're building a business-critical application, we do strongly recommend moving to a Stormpath Enterprise or Private Deployment where we can work with your team directly prior to API releases. We have a historical uptime record of _over five 9s_ on Enterprise deployments and can provide SLAs to meet your requirements.

As always, your feedback is incredibly valuable to me and everyone at Stormpath.  I mean that sincerely.  Please don't hesitate to @ mention me here (@lhazlewood) or  contact us at support@stormpath.com.  We have a very responsive team and you will definitely receive an answer.  Thank you!
