### ISSUE TITLE
CookieAccountResolver and SessionAccountResolver AuthType has FORM type hardcoded

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#429]
Looking at the servlet request API, it appears we are allowed to return an implementation-specific String if desired.  We need to change `AuthType` in both `SessionAccountResolver ` and `CookieAccountResolver ` to be some other string that accurately reflects how they authenticated, for example "jwt" or "jwt-cookie" or "session"

**Comment by maranai** [comment]
Discussed this issue in Today's stand up call. The existing flow and stored cookie does not match the framework spec (https://github.com/stormpath/stormpath-framework-spec/blob/3f9ab47c8e3c5aa81d68903a52f274e952fd2db5/cookie-authentication.md). As per Tom, since this is not currently causing problems to any customer and JSDK should match the framework spec for RC1.0, implying this would be re-factored or discarded, no time should be invested on this change.

**Comment by dogeared** [comment]
Per @maranai's comment, closing this issue.
