### ISSUE TITLE
ResourceReference seems no to be reflecting changes on update

### ISSUE THREAD

**Issue by antollinim** [stormpath/stormpath-sdk-java#47]
I have the suspicion that the Java SDK keeps an old version of the Resources after being modified by another instance.

**Comment by lhazlewood** [comment]
@mrioan I just noticed this implementation uses a SoftHashMap.  Why is that?  The caching tier is the authoritative source for href-to-data record keeping.

**Comment by mrioan** [comment]
@lhazlewood at the time we implemented this, the Cache was disabled by default. 

I will provide you with some insight about the actual problem that this map solved. This map is used to allow Resource Instances to have a link to other Resource Instances. This is not href-to-data but href-to-state link. It is not storing any actual resource data, just an href-to-state pointer to share the same data state with other Resources interacting with the same href.

Before we had this, this scenario was failing:

```groovy
def account = client.getResource(accountHref, Account.class); 
def directory = client.getResource(account.getDirectory().getHref(), Directory.class);

directory.setName(app.getName() + "XXXXX");
directory.save();

//account data has never been retrieved yet

account.getDirectory().getName();

//*1 now the account data has been populated. The account has not a link to the Directory resource instance, it has a copy of all the directory data

assertEquals(directory.getName(), account.getDirectory().getName()); //this is OK

directory.setName(app.getName() + "YYYYY");
directory.save();

//*2 now the directory name has been changed and saved, thus the cache has also the updated dir name

//The account has no idea of the new name of the directory because it already had the name populated in *1. In *2 the dir name has been changed but the Account instance
//does not share the same state of the Directory, it has an outdated copy of the Directory data as of step *1. There is no link between the Resource Instances.

assertEquals(directory.getName(), account.getDirectory().getName()); //Before fixing issue #47, this assertion failed
```

The solution was to add a map to keep a reference to Resource Instances in order to be able to have their data shared among instances. 

Now that you have a better understanding of this, do you think this could really be moved to the cache tier? I am not sure how this will behave when Cache-related things like TTL are added to the equation.
