### ISSUE TITLE
Support an access_token coming in a Cookie

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#474]
Since we switched to Token Management, `access_token`s can only be properly validated when they come in the `Authorization` header. 

A request like this was previously working (1.0.RC8.2) but does not work any longer:

```
GET /stars/pollux
Host: galaxies.com

Cookie: access_token=eyJhbGciOiJIUzI1NiIsI.eyJpc3MiOiJodHRwczotcGxlL.mFrs3Zo8eaSNcxiNfvRh9dqKP4F1cB;
```

The issue is in `DefaultJwtAccountResolverr`

**Comment by mrioan** [comment]
We actually never explicilty supported automatically validating an `access_token` coming in a cookie.

Until `1.0.RC8.2` we were using the same logic to create and validate two different kind of `JWT`s: 1) A real `access_token`, 2) an internally used `account` cookie where we store context for authenticated users (the value of this cookie is a `jwt`).

This meant that if an `access_token` were sent to us in a cookie our `CookieAccountResolver` would have been able to validate it and the `Account` would have been successfully resolved. This was an unintentional feature (or a bug, depending on how you want to see it).

In `1.0.RC.8.3` we integrated [the new token management](https://docs.stormpath.com/guides/token-management/) to the Spring Stack. This changed the way we create and validate `access_tokens` while the `account` cookie remained untouched.

Now, the `jwt` of an `access_token` cannot be validated by `CookieAccountResolver`, which is not actually neither a bug nor a requirement.

Having clarified that, [this post of ours](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/) is encouraging developers to store an `access_token` in a cookie. So, users reading it will be prone to think that the Java SDK does support it. Therefore I am leaving this issue open because we might want to implement this in the future. I am removing the "bug" label though.

**Comment by jaytylerwilliams** [comment]
>This was an unintentional feature (or a bug, depending on how you want to see it).

Why is it unintended?  Tom's blog post clearly seems to lean towards cookies as a more secure way of storing access tokens.  Customer reads this blog post on Stormpath, implements solution mimicking what is found in blog, and it works.  Account gets resolved, all is good.  Now it doesn't.  What is the workaround?  How do we continue to use cookies on the client side to make calls to our API?  Or is the only other option having clients store access token in HTML5 storage and pass in as a Bearer token?  Do we have to write a bunch of code to validate the token from the cookie ourselves and manually resolve the account?  Seems like a hack since the servlet filter will still be called and throw an exception each time a request is made.

**Comment by mrioan** [comment]
Hello Jay,

I understand your frustration but technically speaking the feature you were able to use in `1.0.RC8.2` was not a real feature, you were basically overriding a cookie that we use internally in our code. Overriding this can actually cause some problems, you were basically lucky that none materialized to you yet.

In my comment I mentioned the blog post and I said that this issue was not going to be closed. I simply removed the "bug" label and changed the priority, I included the rationale behind that. We will for sure work on adding the (new, previously unsupported) feature to "allow an access token to come in a cookie". But we need to implement it consciously, that was not the case in `1.0.RC8.2`.

As a work around I can suggest two things: 1) keep using 1.0.RC8.2 until we add this feature, 2) contact us via http://support.stormpath.com and we will provide you with a piece of code that will give you back the functionality that we patched in `1.0.RC8.3`

**Comment by mrioan** [comment]
For reference, we need to be compliant with `https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md`.

**Comment by mrioan** [comment]
Support ticket 6374 (internal) will benefit fro this as well. That ticket is a side-effect of not being spec-compliant

**Comment by jarias** [comment]
I work a bit on this before we reorganize our priorities the work is in this branch https://github.com/stormpath/stormpath-sdk-java/tree/access_token_in_cookie I'll say I had probably 50% fo the work done.

I was keeping the old account cookie as it is.

**Comment by jarias** [comment]
@lhazlewood @mrioan @dogeared As I mention on my status email today, the current impl that I worked on keeps the account cookie and its config as it is and adds the access token and refresh token cookies according to spec. Not sure if that's the path we want to continue on or just remove the account cookie and change the account resolver to use the access token cookie. 

Personally even if it might impact more, I think we should remove the account cookie so we are more in par with the other SDKs. And remove extra code that basically tries to the same, keep the authentication info between requests. Also I think it would only impact users that access the cookie directly for some strange reason, since the account should be resolve using the AccountResolver.

**Comment by dogeared** [comment]
@jarias - Per the [spec page](https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md) on this, the solution needs to not only set access_token and refresh_token as cookies, but also needs to handle the [rejection](https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#rejecting-requests) scenarios. Additionally, it should handle the [cookie flags](https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#rejecting-requests) as well. The spec calls out the required properties.

Specific work on yaml config is not necessary in this issue as it will be addressed by a config-specific issue.

**Comment by jarias** [comment]
Code is ready but to move this forward we need to validate against the TCK which currently depends on JSON content negotiation to be available for the different endpoints, this is needed to register accounts an other setup tasks in the TCK, this is currently been worked in the JSDK #364 ticket.
