### ISSUE TITLE
Fix artificial wait on redirects

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#539]
This occurs because currently, a redirect is treated as a retry.

#538 address this.

**Comment by mrioan** [comment]
Some important operations (like validating an access token) were taking longer than expected. The root cause was that a redirect was being seen as a retry by our network algorithm, which was triggering an exponential pause. Proper handling of retries will noticeable improve performance! Thanks for this finding @dogeared !

**Comment by dogeared** [comment]
:+1:
