### ISSUE TITLE
Support YAML config

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#571]
Per framework spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/configuration.md) and [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/web-config.yaml).

We need to support YAML config in:

* servlet plugin
* Spring (all integrations)
* Spring Boot (all integrations)

**Comment by dogeared** [comment]
Does this imply that we will *not* support `stormpath.properties` in servlet and `application.properties` in spring/spring boot?

**Comment by lhazlewood** [comment]
When spring or spring boot is in play, they can configure things using whatever spring-supported config mechanism they want (.properties, .yaml, JavaConfig, whatever) - we don't have to worry about config in those environments.

Native YAML capability only applies to environments/frameworks that don't already have a config standard, which is currently only the core SDK and the servlet integration.

That said, if you look at the spec, the yaml format (hierarchical property paths) must match exactly, but this would be the case in spring since yaml paths and .properties 'flatten' to be the same thing anyway.

**Comment by dogeared** [comment]
So it seems to me like the implication is that we would morph
stormpath.properties into stormpath.yml and refactor the servlet config
code to use that.

FYI, I've raised an issue in the framework spec about the specific file
name here: https://github.com/stormpath/stormpath-framework-spec/issues/85

**Comment by mraible** [comment]
I believe [this PR](https://github.com/stormpath/stormpath-sdk-java/pull/593) is ready for review in that it satisfies the [YAML requirements for the servlet plugin](https://github.com/stormpath/stormpath-sdk-java/wiki/Overriding-Default-Configuration#servlet-integration).

NOTE: It does nothing to satisfy the following items in the servlet spec:

1. `classpath:com/stormpath/sdk/config/stormpath.properties`
2. `classpath:com/stormpath/sdk/servlet/config/web.stormpath.properties` (it supports `default.stormpath.properties`, but not `web.stormpath.properties`)
3. `classpath:stormpath.json`
4. `classpath:stormpath.yml`
5. `/WEB-INF/stormpath.json`
6. `$HOME/.stormpath/stormpath.json`
7. `$HOME/.stormpath/stormpath.yml`
8. `System.getProperty("user.dir") + File.separator + "stormpath.json"`
9. `System.getProperty("user.dir") + File.separator + "stormpath.yml"`

I believe that 1, 4, 7 and 9 should all be solved in the core SDK (possibly in `ClientApiKeyBuilder`?).

I believe that 3, 5, 6 and 8 should be solved by another ticket for JSON configuration support.

**Comment by lhazlewood** [comment]
The extension in the spec currently for yaml is `.yaml` not `.yml`.  Is there one that should be used over the other?  I thought Spring (for example) uses `.yaml`.  Thoughts?

**Comment by mraible** [comment]
@lhazlewood You are correct, http://www.yaml.org/faq.html recommends `.yaml` over `.yml`. Spring Boot uses `.yml`, that's the reason I used that extension. See [Application property files)[https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files] and [JHipster's default config](https://github.com/jhipster/generator-jhipster/tree/master/generators/server/templates/src/main/resources/config) for reference.

**Comment by mraible** [comment]
It looks like `.yml` is used 3x as much as `.yaml` http://stackoverflow.com/questions/21059124/is-it-yaml-or-yml

**Comment by lhazlewood** [comment]
Our [framework spec](https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/config.md) indicates `.yaml`.  If we don't do this, it won't be consistent across app deployments of different languages and likely to confuse people.

Given that the YAML maintainers have even given a recommendation, plus due to the fact that other Stormpath teams have built it already, I think we need to stick with `.yaml`

**Comment by mraible** [comment]
OK, I'll change it to .yaml.
