### ISSUE TITLE
Social Login throws error if Verification Workflow is enabled

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#751]
I see the following exception after login for the first time (Registration) with a Google Account if the Google Directory has the verification workflow enabled

```
Unable to invoke Stormpath core controller: HTTP 400, Stormpath 10010 
(https://docs.stormpath.com/rest/product-guide/latest/errors.html#error-10010), RequestId XXXXX: Token is no longer valid because the Account is not enabled.
```

**Comment by mdeggies** [comment]
This happens because our system tries to log the user in automatically after a first-time social login (aka registration). If you have the verification workflow enabled, the user's account hasn't been verified yet and cannot be logged in. 

Is your app crashing when this error is thrown? I believe the expected behavior is that the 'Token is Invalid' error is thrown on the front-end, but your app should not crash.

**Comment by mrioan** [comment]
The exception is happening in the Java SDK and failing ungracefully. It should be validating that the account is enabled before allowing the authentication flow to continue. I THINK the problem is that it is trying to obtain the access token in order to create the cookie. But the backend does not allow that since the account is still not verified.
