### ISSUE TITLE
Our Spring Security Authenticated Object depends on the Stormpath Spring Sec library

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#769]
Inside the `Authentication` object we put an `StormpathUserDetails` instance. This means that customer's code stays dependent on our Stormpath Spring Security library in order to be able to obtain Authentication data.

I am milestoning it for `1.0.0` because a change like this will cause customer's code to break.

For reference: ticket 8291

**Comment by snowe2010** [comment]
I reported this to Mario initially. The detailed scenario is that we have a gateway where Stormpath should reside. None of our microservices should depend on it. If we add any custom permissions to the Account though, we get unwrapping issues in our microservices since they do not have any knowledge of Stormpath. It seems that Stormpath is using custom `Permission`s for somethings, in our case it was `WildcardPermission`.

Hopefully this info helps fix the issue.

**Comment by lhazlewood** [comment]
Thanks for the issue!  But I'm really confused :)  Can you help me understand the problem?

I mean, doesn't Spring Security expect you to add UserDetails to the Authentication object?  How else would it work?

Maybe another way of questioning:  what is the proposed change in the Stormpath Spring Security module if this shouldn't be the case?  Thanks!
