### ISSUE TITLE
Remove DefaultSamlProviderModelFactory

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#771]
This executes a query and only returns SAML account store models in order to make a warning/show an error.

However just a few lines below its use, the other `AccountStoreModelFactory` also queries for all account stores and returns those models.

There is no need to execute these queries twice.  Just use the first/original factory, and then iterate over it to check for the warning condition and add an error if necessary.

Until this is done, at least two queries to Stormpath are made on every login page rendering, when only one is necessary.

**Comment by mraible** [comment]
@lhazlewood This only executes a query when Site ID and Callbacks are disabled (as required by #748), so it might not happen on _every_ login page rendering.

```java
// 748: If stormpath.web.idSite.enabled is false and stormpath.web.callback.enabled is false AND
// there are SAML directories mapped to the application, that is a configuration error.
if (!idSiteEnabled && !callbackEnabled) {
```

`DefaultSamlProviderModelFactory` is for just selecting SAML stores, since that's all we care about in the above logic block. 

If there is a way to call `accountStoreModelFactory.getAccountStores(request)` and then see if they're SAML stores, it makes sense to make this change. When I wrote this code, I didn't see a way to find out if a store was SAML vs. Social. 

/cc @dogeared

**Comment by lhazlewood** [comment]
@mraible if you look inside the factory implementation, in the Visitor, you can see how the provider is being checked to create an appropriate `AccountStoreModel` instance.  When the list of `AccountStoreModel`s is returned, you can check `accountStore.provider.providerId == 'saml'`.  I'll be making this change in my local branch, so no need to implement it, but I thought I'd explain how you can tell for future scenarios.  Cheers!
