### ISSUE TITLE
Timeout in properties file is expected in secs but milliseconds when programmatically

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#920]
At least this is what @josebarrueta and me discovered while being confused about documentation and code.

We need to validate that this is actually a problem and if true we need to use seconds everywhere (milliseconds seems to much granular with no real reason)

`DefaultClientBuilder` has this (note `*1000`):
```
if (props.get(DEFAULT_CLIENT_CONNECTION_TIMEOUT_PROPERTY_NAME) != null) {
            clientConfig.setConnectionTimeout(Integer.valueOf(props.get(DEFAULT_CLIENT_CONNECTION_TIMEOUT_PROPERTY_NAME)) * 1000);
        }
```

On the other hand `ClientBuilder#setConnectionTimeout` says this in its javadoc:

```
* @param timeout connection and socket timeout in milliseconds
```

Additionally be sure that documentation is also updated if required

**Comment by josebarrueta** [comment]
Also, somewhere in the Client or the ClientBuilder, we should state what the default is. 

I agree with @mrioan that seconds might be good, we just need to be aware to convert it to ms in the back, such as we configure the HttpClient correctly.

**Comment by mraible** [comment]
`HttpClientRequestExecutor` uses this value to set the connectionTimeout on `DefaultHttpClient`, which also uses milliseconds. 

https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/params/CoreConnectionPNames.html#CONNECTION_TIMEOUT

Are you suggesting the fix is to remove "* 1000" and multiple the existing property by 1000?
